name: Clean Docs via reusable workflow

on:
  workflow_dispatch:

jobs:
  call-cleaner:
    uses: e1970180/clean-docs-for-gpt/.github/workflows/reusable-cleaner.yml@main
    with:
      config_path: .clean-docs-for-gpt_config.yml