name: Run Clean Docs from External Repo

on:
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  run-cleaner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone clean-docs-for-gpt tools
        uses: actions/checkout@v4
        with:
          repository: e1970180/clean-docs-for-gpt
          path: .external-tools/clean-docs-for-gpt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run cleaner from clean-docs-for-gpt
        run: |
          python .external-tools/clean-docs-for-gpt/scripts/clean_markdown.py .clean-docs-for-gpt_config.yml
      - name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "docs: update cleaned documentation" || echo "nothing to commit"
          git push || echo "nothing to push"
